// <auto-generated>
//     Generated by .github/scripts/audit/generate_defensive_values.py from the effect
//     texts in RotationSolver.SourceGenerators/Properties. Do not edit by hand - CI
//     regenerates this file and fails when it no longer matches the effect texts.
//
//     What each figure means, because the three are NOT interchangeable:
//       Self             - the bearer takes this share less of any hit
//       EnemyPhysical /  - the attacker deals this share less; two figures because Addle
//       EnemyMagical       and Feint split by damage type
//       Barrier          - absorbs this share of the target's MAXIMUM health, in points:
//                          more than enough against a small hit, spent against a big one
// </auto-generated>

namespace RotationSolver.Basic.Data;

/// <summary>
/// What one defensive action takes off an incoming hit, as stated in its own effect text.
/// A value of 0 means the effect text does not state that kind of figure - never that the
/// action does nothing.
/// </summary>
public readonly record struct DefensiveValue(
	float Self,
	float EnemyPhysical,
	float EnemyMagical,
	float Barrier);

/// <summary>
/// The stated figures of every defensive action, keyed by action row id, generated from the
/// effect texts. Read through <see cref="For"/> rather than the dictionary, so an action
/// the texts do not rate answers with zeroes instead of throwing.
/// </summary>
public static class DefensiveValues
{
	/// <summary>Action row id to the figures its effect text states.</summary>
	public static readonly Dictionary<uint, DefensiveValue> ByActionId = new()
	{
		[17] = new(0.3f, 0f, 0f, 0f), // SentinelPvE
		[44] = new(0.3f, 0f, 0f, 0f), // VengeancePvE
		[157] = new(0f, 0f, 0f, 0.3f), // ManawardPvE
		[2887] = new(0f, 0.1f, 0.1f, 0f), // DismantlePvE
		[3540] = new(0f, 0f, 0f, 0.1f), // DivineVeilPvE
		[3542] = new(0.15f, 0f, 0f, 0f), // SheltronPvE
		[3551] = new(0.1f, 0f, 0f, 0f), // RawIntuitionPvE
		[3613] = new(0.1f, 0f, 0f, 0f), // CollectiveUnconsciousPvE
		[3636] = new(0.3f, 0f, 0f, 0f), // ShadowWallPvE
		[7388] = new(0f, 0f, 0f, 0.15f), // ShakeItOffPvE
		[7393] = new(0f, 0f, 0f, 0.25f), // TheBlackestNightPvE
		[7394] = new(0.2f, 0f, 0f, 0f), // RiddleOfEarthPvE
		[7433] = new(0.1f, 0f, 0f, 0f), // PlenaryIndulgencePvE
		[7531] = new(0.2f, 0f, 0f, 0f), // RampartPvE
		[7535] = new(0f, 0.1f, 0.1f, 0f), // ReprisalPvE
		[7549] = new(0f, 0.1f, 0.05f, 0f), // FeintPvE
		[7560] = new(0f, 0.05f, 0.1f, 0f), // AddlePvE
		[11417] = new(0.4f, 0.4f, 0.4f, 0f), // MightyGuardPvE
		[11424] = new(0.9f, 0f, 0f, 0f), // DiamondbackPvE
		[12960] = new(0.8f, 0f, 0f, 0f), // WisdomOfThePlatebearerPvE
		[12961] = new(0.45f, 0f, 0f, 0f), // WisdomOfTheGuardianPvE
		[12991] = new(0f, 0f, 0f, 0.1f), // StoneskinLPvE
		[14480] = new(0.64f, 0f, 0f, 0f), // WisdomOfTheIndomitablePvE
		[16140] = new(0.1f, 0f, 0f, 0f), // CamouflagePvE
		[16148] = new(0.3f, 0f, 0f, 0f), // NebulaPvE
		[16464] = new(0.1f, 0f, 0f, 0f), // NascentFlashPvE
		[20495] = new(0.5f, 0f, 0f, 0f), // AetherialAegisPvE
		[20703] = new(0.9f, 0f, 0f, 0f), // LostManawallPvE
		[20712] = new(0f, 0f, 0f, 0.15f), // LostStoneskinPvE
		[20722] = new(0.3f, 0f, 0f, 0f), // BannerOfTirelessConvictionPvE
		[20723] = new(0.3f, 0.15f, 0.15f, 0f), // BannerOfFirmResolvePvE
		[21611] = new(0.1f, 0f, 0f, 0f), // FixedSignPvE
		[22354] = new(0f, 0.6f, 0.6f, 0f), // LostSeraphStrikePvE
		[23273] = new(0.2f, 0f, 0f, 0f), // ChelonianGatePvE
		[23280] = new(0.2f, 0f, 0f, 0f), // DragonForcePvE
		[23908] = new(0f, 0f, 0f, 0.1f), // LostStoneskinIiPvE
		[23921] = new(0.05f, 0f, 0f, 0f), // LostBloodRagePvE
		[24404] = new(0f, 0f, 0f, 0.1f), // ArcaneCrestPvE
		[25746] = new(0.15f, 0f, 0f, 0f), // HolySheltronPvE
		[25751] = new(0.1f, 0f, 0f, 0f), // BloodwhettingPvE
		[25758] = new(0.15f, 0f, 0f, 0f), // HeartOfCorundumPvE
		[25799] = new(0f, 0f, 0f, 0.2f), // RadiantAegisPvE
		[25868] = new(0.1f, 0f, 0f, 0f), // ExpedientPvE
		[29733] = new(0.2f, 0f, 0f, 0f), // VariantRampartPvE
		[34685] = new(0f, 0f, 0f, 0.2f), // TemperaCoatPvE
		[34686] = new(0f, 0f, 0f, 0.1f), // TemperaGrassaPvE
		[36920] = new(0.4f, 0f, 0f, 0f), // GuardianPvE
		[36923] = new(0.4f, 0f, 0f, 0f), // DamnationPvE
		[36927] = new(0.4f, 0f, 0f, 0f), // ShadowedVigilPvE
		[36935] = new(0.4f, 0f, 0f, 0f), // GreatNebulaPvE
		[36962] = new(0.1f, 0f, 0f, 0f), // TengentsuPvE
		[41610] = new(0.1f, 0f, 0f, 0f), // HerosRimePvE
		[44899] = new(0f, 0.1f, 0.1f, 0f), // SeedsowerPvE
		[46412] = new(0.6f, 0f, 0f, 0f), // ThickSkinPvE
		[46590] = new(0f, 0f, 0f, 0.2f), // MagicShellPvE
		[46595] = new(0.5f, 0f, 0f, 0f), // DefendPvE
		[46604] = new(0f, 0f, 0f, 0.1f), // SteadfastStancePvE
		[46605] = new(0f, 0.1f, 0.1f, 0f), // MesmerizePvE
		[46606] = new(0.1f, 0f, 0f, 0f), // InquiringMindPvE
		[49075] = new(0f, 0.99f, 0.99f, 0f), // OccultToadPvE
	};

	/// <summary>The figures for this action, or all zeroes when it states none.</summary>
	public static DefensiveValue For(uint actionId)
	{
		return ByActionId.TryGetValue(actionId, out var value) ? value : default;
	}

	/// <summary>
	/// The largest barrier share an action states in its own effect text, among barriers
	/// that can be put on another party member. This is the measure of "a big hit": an
	/// area action that costs at least this much of maximum health is more than a large
	/// shield on the member hit can absorb. A barrier only its caster carries is left out.
	/// </summary>
	/// <remarks>
	/// Computed from the table rather than written down, so a patch that restates a barrier
	/// or a new job action with a larger one moves the threshold with it. The figure is
	/// regenerated from the effect texts and checked against them in CI.
	/// </remarks>
	public const float LargestStatedBarrierShare = 0.25f;

	/// <summary>
	/// How long each defensive action's effect stands, in seconds, as its effect text states
	/// it. Missing where the text states no number - a trait that changes the duration leaves
	/// the text blank - so a caller never reads a figure the game did not give.
	/// </summary>
	public static readonly Dictionary<uint, float> DurationByActionId = new()
	{
		[17] = 15f, // SentinelPvE
		[44] = 15f, // VengeancePvE
		[157] = 20f, // ManawardPvE
		[2887] = 10f, // DismantlePvE
		[3540] = 30f, // DivineVeilPvE
		[3551] = 6f, // RawIntuitionPvE
		[3613] = 18f, // CollectiveUnconsciousPvE
		[3636] = 15f, // ShadowWallPvE
		[7388] = 30f, // ShakeItOffPvE
		[7393] = 7f, // TheBlackestNightPvE
		[7394] = 10f, // RiddleOfEarthPvE
		[7433] = 10f, // PlenaryIndulgencePvE
		[7531] = 20f, // RampartPvE
		[11424] = 10f, // DiamondbackPvE
		[12991] = 30f, // StoneskinLPvE
		[16140] = 20f, // CamouflagePvE
		[16148] = 15f, // NebulaPvE
		[20703] = 6f, // LostManawallPvE
		[20712] = 60f, // LostStoneskinPvE
		[20722] = 30f, // BannerOfTirelessConvictionPvE
		[20723] = 30f, // BannerOfFirmResolvePvE
		[21611] = 18f, // FixedSignPvE
		[22354] = 15f, // LostSeraphStrikePvE
		[23273] = 10f, // ChelonianGatePvE
		[23280] = 15f, // DragonForcePvE
		[23908] = 30f, // LostStoneskinIiPvE
		[23921] = 18f, // LostBloodRagePvE
		[24404] = 5f, // ArcaneCrestPvE
		[25746] = 8f, // HolySheltronPvE
		[25751] = 8f, // BloodwhettingPvE
		[25758] = 8f, // HeartOfCorundumPvE
		[25799] = 30f, // RadiantAegisPvE
		[25868] = 10f, // ExpedientPvE
		[29733] = 60f, // VariantRampartPvE
		[34685] = 10f, // TemperaCoatPvE
		[34686] = 10f, // TemperaGrassaPvE
		[36920] = 15f, // GuardianPvE
		[36923] = 15f, // DamnationPvE
		[36927] = 15f, // ShadowedVigilPvE
		[36935] = 15f, // GreatNebulaPvE
		[36962] = 4f, // TengentsuPvE
		[41610] = 20f, // HerosRimePvE
		[44899] = 60f, // SeedsowerPvE
		[46412] = 4f, // ThickSkinPvE
		[46590] = 60f, // MagicShellPvE
		[46595] = 5f, // DefendPvE
		[46604] = 30f, // SteadfastStancePvE
		[46605] = 4f, // MesmerizePvE
		[49075] = 20f, // OccultToadPvE
	};

	/// <summary>The stated duration in seconds, or 0 when the effect text states none.</summary>
	public static float DurationOf(uint actionId)
	{
		return DurationByActionId.TryGetValue(actionId, out var seconds) ? seconds : 0f;
	}
}
